// Generated by Wrangler on Tue Mar 26 2024 12:45:49 GMT-0300 (Brasilia Standard Time)
// by running `wrangler types`

interface Env {
	SUPABASE_URL: "https://ylgebhltybpticywvzif.supabase.co";
	AI: unknown;
}
