// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface Env extends Record<string, any> {
	// bindings are generated by `wrangler types`
	SUPABASE_URL: string;
	SUPABASE_KEY: string;

}

export const AI_MODEL = '@hf/thebloke/neural-chat-7b-v3-1-awq' as const
export const EMBEDDINGS_MODEL = '@cf/baai/bge-base-en-v1.5' as const
export const VECTOR_DIM = 768
export const SIMILARITY_CUTOFF = 0.75

// Information about embeddings vectors
// export const Vectors = {
// 	bge: {
// 		dimensions: {
// 			small: 384,
// 			base: 768,
// 			large: 1024
// 		}
// 	},
// 	gte: {
// 		dimensions: {
// 			small: 384,
// 			base: 768,
// 			large: 1024
// 		}
// 	}
// } as const

export interface HonoEnv {
	Bindings: Env
}
